name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run test
      - run: echo SUCCESS
